remote_theme: pmarsceill/just-the-docs
aux_links:
  "MBARI":
    - "http://www.mbari.org"
  "MBARI Media Management":
    - "//github.com/mbari-media-management"
  "Source":
    - "//github.com/mbari-media-management/vars-annotation"
color_scheme: "dark"
heading_anchors: true
logo: "resources/images/mbari-logo.png"
search_enabled: true
